// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdnhwnmbsdaqmvoqsppy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtkbmh3bm1ic2RhcW12b3FzcHB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDYyNDksImV4cCI6MjA1ODMyMjI0OX0.1Zq-Xizi9F8KsueScJdvukR1AgllQ3iuYqdF1TVJ70o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);