
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzuloriouwirmaxateto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6dWxvcmlvdXdpcm1heGF0ZXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODU5OTUsImV4cCI6MjA1ODE2MTk5NX0._hLpk3HrvT4X5h2mzZ5XHfhzQFFOndLA_Zl0RFfuybg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to create chart data - using raw API calls instead of typed client
export async function createOrGetChartData() {
  // Check if chart data exists using a stored procedure
  const { data: existingData, error: checkError } = await supabase.rpc('check_chart_data_exists');

  if (checkError) {
    console.error('Error checking chart data:', checkError);
    return;
  }

  if (existingData && existingData.length > 0) {
    console.log('Chart data already exists');
    return;
  }

  // If no data exists, invoke the edge function to create it
  const { data, error } = await supabase.functions.invoke('initialize-chart-data');
  
  if (error) {
    console.error('Error initializing chart data:', error);
    return;
  }
  
  console.log('Chart data created successfully:', data);
}
